// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrygGbcvvxwniIkzU2HThVe8Xrk4_PXAU',
    appId: '1:310251073945:web:dccff3b08bb7108169e308',
    messagingSenderId: '310251073945',
    projectId: 'chat-app2-e9f25',
    authDomain: 'chat-app2-e9f25.firebaseapp.com',
    storageBucket: 'chat-app2-e9f25.appspot.com',
    measurementId: 'G-TKBD0KHSZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRpAt5Vja7dOzB9qnsoqGP5yTdDXvI5lw',
    appId: '1:310251073945:android:f5d3249f09383fa269e308',
    messagingSenderId: '310251073945',
    projectId: 'chat-app2-e9f25',
    storageBucket: 'chat-app2-e9f25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD88_AGYXB65EvV5RxLtHpE6fn9IR4UF8',
    appId: '1:310251073945:ios:0921137051b3ac5069e308',
    messagingSenderId: '310251073945',
    projectId: 'chat-app2-e9f25',
    storageBucket: 'chat-app2-e9f25.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD88_AGYXB65EvV5RxLtHpE6fn9IR4UF8',
    appId: '1:310251073945:ios:6b9e1a7da91791a269e308',
    messagingSenderId: '310251073945',
    projectId: 'chat-app2-e9f25',
    storageBucket: 'chat-app2-e9f25.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
